#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("xam.colorDialog.Resource", IsApplication=false)]

namespace xam.colorDialog
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public static int color_dialog_content = 2131034113;
			
			// aapt resource value: 0x7f050003
			public static int color_dialog_content_prompt = 2131034115;
			
			// aapt resource value: 0x7f050000
			public static int color_dialog_gray = 2131034112;
			
			// aapt resource value: 0x7f050002
			public static int color_dialog_title = 2131034114;
			
			// aapt resource value: 0x7f050005
			public static int color_type_help = 2131034117;
			
			// aapt resource value: 0x7f050004
			public static int color_type_info = 2131034116;
			
			// aapt resource value: 0x7f050008
			public static int color_type_success = 2131034120;
			
			// aapt resource value: 0x7f050007
			public static int color_type_warning = 2131034119;
			
			// aapt resource value: 0x7f050006
			public static int color_type_wrong = 2131034118;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int sel_btn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int sel_btn_help = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int sel_btn_info = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int sel_btn_success = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int sel_btn_warning = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int sel_btn_wrong = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int sel_def_gray = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int sel_def_gray_left = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int sel_def_gray_right = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int shape_corners_bottom = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int shape_corners_bottom_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int shape_left_bottom = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int shape_left_bottom_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int shape_right_bottom = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int shape_right_bottom_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int shape_top = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public static int btnNegative = 2131230729;
			
			// aapt resource value: 0x7f080007
			public static int btnPositive = 2131230727;
			
			// aapt resource value: 0x7f080008
			public static int divider = 2131230728;
			
			// aapt resource value: 0x7f080004
			public static int ivContent = 2131230724;
			
			// aapt resource value: 0x7f080001
			public static int llBkg = 2131230721;
			
			// aapt resource value: 0x7f080006
			public static int llBtnGroup = 2131230726;
			
			// aapt resource value: 0x7f080003
			public static int llContent = 2131230723;
			
			// aapt resource value: 0x7f08000a
			public static int llTop = 2131230730;
			
			// aapt resource value: 0x7f080000
			public static int loading = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public static int logoIv = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public static int topLayout = 2131230732;
			
			// aapt resource value: 0x7f080005
			public static int tvContent = 2131230725;
			
			// aapt resource value: 0x7f080002
			public static int tvTitle = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public static int layout_colordialog = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int layout_promptdialog = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public static int ic_help = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int ic_info = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int ic_success = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int ic_wrong = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int icon_warning = 2130903044;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public static int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public static int color_dialog = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
